from django.urls import path
from app_api import views

urlpatterns = [
    path('add-jd', views.addJD),
    path('update-jd-data', views.jdUpdateData),
    path('update-jd', views.updateJD),
    path('add-companydata', views.addCompanyData),
    # path('add-jd-candidate', views.addJDCandidate),
    path('register-user',views.registerUser),
    path('jd-add-or-update-test',views.jdAddTest),
    path('login-user',views.loginUser),
    path('get-jd-workflow',views.getJdWorkflow),
    path('get-jd-screening-questions',views.getJdQuestionsView), #
    path('add-candidate',views.addCandidate),
    path('interview-scheduling/<int:cid>',views.interviewScheduling),
    path('schedule-interview',views.scheduleInterviewView),
    # path('work-flow-data',views.workFlowData),
    path('work-flow-data',views.workFlowData),
    path('candidate-registration-cdn/<str:enc_jdid>/',views.candidateRegistrationCDNForm),
    path('register-candidate',views.registerCandidate),
    path('evaluation',views.evaluationView),
    path('interview-response',views.interviewResponseView),
    path('questions-response',views.questionsResponseView),
    path('get-interview-status',views.getInterviewStatusView),
    path('interview-file',views.interviewFile),
    path('interview-completion',views.interviewCompletion),
    path('interview-feedback',views.interviewFeedback),
    path('check-test-has-paper',views.checkTestHasPaper),
    path('get-candidate-report',views.candidateReport),
    path('delete-test-injd',views.deleteTestinJs),
    path('save-interviewers-lst',views.saveInterviewersForJd),
    path('notify-candidate',views.notifyCandidate),
    path('get-update-company-credits',views.getUpdateCompanyCreditsView),   
    path('get-credits',views.getCreditsView),
    path('jd-publish',views.jdPublish),
    path('update-company-branding',views.updateCompanyBrandingView),
    path('get-user-name',views.getUserName),
    path('update-hirelines-data',views.updateHirelinesData),
    path('interview-remarks',views.interviewRemarkSave),

    path('add-new-user',views.addNewUsers),
    path('change-user-status',views.changeUserStatus),

    path('update-emailtemp',views.updateEmailtemp),
    path('get-jddata',views.getJDData),
    path('update-company',views.updateCompany),

    path('demo-user',views.demoUser),
    path('req-demo',views.demoRequest),
    path('delete-candidate',views.deleteCandidate),
    path('update-candidate-workflow',views.updateCandidateWorkflow),
    path('dashboard-graph-data',views.getDashboardGraphData),
    path('make-star-question',views.makeAstarQuestion),
    path('update-candidate-info',views.updateCandidateInfo),
    path('update-source-data',views.updateSourceData),
    path('candidate-upload-file',views.candidateUploadFile),
    path('confirmed-candidates-data',views.confirmedCandidateData),
    path('display-dashboardflag',views.updateDashboardDisplayFlag),
    path('skills-topics-subtopics-withquestions',views.skillsWithTopicwithSubtopics),
    path('check-jd-candidate-registration',views.checkJdCandidateRegistration),
    path('download-upload-report',views.downloadUploadReport),
    path("get_paperid",views.get_paperid),
    path("get-gmail-resume/<int:rid>",views.getResumeFile),
    path("get-filter-resume",views.getFilterResumes),
    path("delete-resume",views.deleteResume),

    path("add-resume-profile",views.addResumeProfile),
    path("add-profile",views.addProfile),
    path("update-profile",views.updateProfileDetails),
    path("update-education",views.updateProfileEducation),
    path("update-experience",views.updateProfileExperience),
    path("update-projects",views.updateProfileProjects),
    path("update-awards",views.updateProfileAwards),
    path("update-certifications",views.updateProfileCertificates),
    path("update-skills",views.updateProfileSkills),
    path("get_paperid",views.get_paperid),
    path("profile-filters",views.filter_profiles_api),
    path('get-default-email-template',views.getDefaultEmailTemplate),
    path('add-profile-activity',views.addProfileActivity),
    path('candidate-profile',views.candidateProfile),
    path("send-welcome-mail",views.sendwelcomemail),
    path("check-welcome-mail-status",views.check_welcome_mail_status),
    
    path("get-work-cal",views.getworkcal),
    path("save-work-cal",views.saveworkcal),
    path('delete-work-cal/<int:id>', views.delete_work_cal),

   



    path('get-mail-resumes',views.getMailResumes),
    path('download-branded-profile',views.downloadBrandedProfile),
]